#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sac")]
	public partial class Conta : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTablaPeriodo(TablaPeriodo instance);
    partial void UpdateTablaPeriodo(TablaPeriodo instance);
    partial void DeleteTablaPeriodo(TablaPeriodo instance);
    partial void InsertCuentaDet(CuentaDet instance);
    partial void UpdateCuentaDet(CuentaDet instance);
    partial void DeleteCuentaDet(CuentaDet instance);
    partial void InsertPresupuestoGastos(PresupuestoGastos instance);
    partial void UpdatePresupuestoGastos(PresupuestoGastos instance);
    partial void DeletePresupuestoGastos(PresupuestoGastos instance);
    partial void InsertCuentaEnc(CuentaEnc instance);
    partial void UpdateCuentaEnc(CuentaEnc instance);
    partial void DeleteCuentaEnc(CuentaEnc instance);
    #endregion
		
		public Conta() : 
				base(global::SAC.Properties.Settings.Default.sacConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public Conta(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Conta(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Conta(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Conta(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TablaPeriodo> TablaPeriodo
		{
			get
			{
				return this.GetTable<TablaPeriodo>();
			}
		}
		
		public System.Data.Linq.Table<CuentaDet> CuentaDet
		{
			get
			{
				return this.GetTable<CuentaDet>();
			}
		}
		
		public System.Data.Linq.Table<PresupuestoGastos> PresupuestoGastos
		{
			get
			{
				return this.GetTable<PresupuestoGastos>();
			}
		}
		
		public System.Data.Linq.Table<CuentaEnc> CuentaEnc
		{
			get
			{
				return this.GetTable<CuentaEnc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Periodo")]
	public partial class TablaPeriodo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPeriodo;
		
		private System.Nullable<int> _mes;
		
		private System.Nullable<int> _anio;
		
		private System.Nullable<char> _status;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPeriodoChanging(int value);
    partial void OnidPeriodoChanged();
    partial void OnmesChanging(System.Nullable<int> value);
    partial void OnmesChanged();
    partial void OnanioChanging(System.Nullable<int> value);
    partial void OnanioChanged();
    partial void OnstatusChanging(System.Nullable<char> value);
    partial void OnstatusChanged();
    #endregion
		
		public TablaPeriodo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPeriodo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPeriodo
		{
			get
			{
				return this._idPeriodo;
			}
			set
			{
				if ((this._idPeriodo != value))
				{
					this.OnidPeriodoChanging(value);
					this.SendPropertyChanging();
					this._idPeriodo = value;
					this.SendPropertyChanged("idPeriodo");
					this.OnidPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mes", DbType="Int")]
		public System.Nullable<int> mes
		{
			get
			{
				return this._mes;
			}
			set
			{
				if ((this._mes != value))
				{
					this.OnmesChanging(value);
					this.SendPropertyChanging();
					this._mes = value;
					this.SendPropertyChanged("mes");
					this.OnmesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int")]
		public System.Nullable<int> anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this.OnanioChanging(value);
					this.SendPropertyChanging();
					this._anio = value;
					this.SendPropertyChanged("anio");
					this.OnanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(1)")]
		public System.Nullable<char> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CuentaDet")]
	public partial class CuentaDet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDetalle;
		
		private System.Nullable<int> _idCuenta;
		
		private System.Nullable<int> _idPeriodo;
		
		private System.Nullable<double> _SaldoInicial;
		
		private System.Nullable<double> _SaldoFinal;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDetalleChanging(int value);
    partial void OnidDetalleChanged();
    partial void OnidCuentaChanging(System.Nullable<int> value);
    partial void OnidCuentaChanged();
    partial void OnidPeriodoChanging(System.Nullable<int> value);
    partial void OnidPeriodoChanged();
    partial void OnSaldoInicialChanging(System.Nullable<double> value);
    partial void OnSaldoInicialChanged();
    partial void OnSaldoFinalChanging(System.Nullable<double> value);
    partial void OnSaldoFinalChanged();
    #endregion
		
		public CuentaDet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDetalle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDetalle
		{
			get
			{
				return this._idDetalle;
			}
			set
			{
				if ((this._idDetalle != value))
				{
					this.OnidDetalleChanging(value);
					this.SendPropertyChanging();
					this._idDetalle = value;
					this.SendPropertyChanged("idDetalle");
					this.OnidDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCuenta", DbType="Int")]
		public System.Nullable<int> idCuenta
		{
			get
			{
				return this._idCuenta;
			}
			set
			{
				if ((this._idCuenta != value))
				{
					this.OnidCuentaChanging(value);
					this.SendPropertyChanging();
					this._idCuenta = value;
					this.SendPropertyChanged("idCuenta");
					this.OnidCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPeriodo", DbType="Int")]
		public System.Nullable<int> idPeriodo
		{
			get
			{
				return this._idPeriodo;
			}
			set
			{
				if ((this._idPeriodo != value))
				{
					this.OnidPeriodoChanging(value);
					this.SendPropertyChanging();
					this._idPeriodo = value;
					this.SendPropertyChanged("idPeriodo");
					this.OnidPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoInicial", DbType="Float")]
		public System.Nullable<double> SaldoInicial
		{
			get
			{
				return this._SaldoInicial;
			}
			set
			{
				if ((this._SaldoInicial != value))
				{
					this.OnSaldoInicialChanging(value);
					this.SendPropertyChanging();
					this._SaldoInicial = value;
					this.SendPropertyChanged("SaldoInicial");
					this.OnSaldoInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoFinal", DbType="Float")]
		public System.Nullable<double> SaldoFinal
		{
			get
			{
				return this._SaldoFinal;
			}
			set
			{
				if ((this._SaldoFinal != value))
				{
					this.OnSaldoFinalChanging(value);
					this.SendPropertyChanging();
					this._SaldoFinal = value;
					this.SendPropertyChanged("SaldoFinal");
					this.OnSaldoFinalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PresupuestoGastos")]
	public partial class PresupuestoGastos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPresupuesto;
		
		private System.Nullable<int> _idCuenta;
		
		private System.Nullable<int> _idPeriodo;
		
		private System.Nullable<double> _saldoInicialAprobado;
		
		private System.Nullable<double> _saldoFinalAprobado;
		
		private System.Nullable<double> _saldoInicialXEjercer;
		
		private System.Nullable<double> _saldoFinalXEjercer;
		
		private System.Nullable<double> _saldoInicialModificado;
		
		private System.Nullable<double> _saldoFinalModificado;
		
		private System.Nullable<double> _saldoInicialComprometido;
		
		private System.Nullable<double> _saldoFinalComprometido;
		
		private System.Nullable<double> _saldoInicalDevengado;
		
		private System.Nullable<double> _saldoFinalDevengado;
		
		private System.Nullable<double> _saldoInicialEjercido;
		
		private System.Nullable<double> _saldoFinalEjercido;
		
		private System.Nullable<double> _saldoInicialPagado;
		
		private System.Nullable<double> _saldoFinalPagado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPresupuestoChanging(int value);
    partial void OnidPresupuestoChanged();
    partial void OnidCuentaChanging(System.Nullable<int> value);
    partial void OnidCuentaChanged();
    partial void OnidPeriodoChanging(System.Nullable<int> value);
    partial void OnidPeriodoChanged();
    partial void OnsaldoInicialAprobadoChanging(System.Nullable<double> value);
    partial void OnsaldoInicialAprobadoChanged();
    partial void OnsaldoFinalAprobadoChanging(System.Nullable<double> value);
    partial void OnsaldoFinalAprobadoChanged();
    partial void OnsaldoInicialXEjercerChanging(System.Nullable<double> value);
    partial void OnsaldoInicialXEjercerChanged();
    partial void OnsaldoFinalXEjercerChanging(System.Nullable<double> value);
    partial void OnsaldoFinalXEjercerChanged();
    partial void OnsaldoInicialModificadoChanging(System.Nullable<double> value);
    partial void OnsaldoInicialModificadoChanged();
    partial void OnsaldoFinalModificadoChanging(System.Nullable<double> value);
    partial void OnsaldoFinalModificadoChanged();
    partial void OnsaldoInicialComprometidoChanging(System.Nullable<double> value);
    partial void OnsaldoInicialComprometidoChanged();
    partial void OnsaldoFinalComprometidoChanging(System.Nullable<double> value);
    partial void OnsaldoFinalComprometidoChanged();
    partial void OnsaldoInicalDevengadoChanging(System.Nullable<double> value);
    partial void OnsaldoInicalDevengadoChanged();
    partial void OnsaldoFinalDevengadoChanging(System.Nullable<double> value);
    partial void OnsaldoFinalDevengadoChanged();
    partial void OnsaldoInicialEjercidoChanging(System.Nullable<double> value);
    partial void OnsaldoInicialEjercidoChanged();
    partial void OnsaldoFinalEjercidoChanging(System.Nullable<double> value);
    partial void OnsaldoFinalEjercidoChanged();
    partial void OnsaldoInicialPagadoChanging(System.Nullable<double> value);
    partial void OnsaldoInicialPagadoChanged();
    partial void OnsaldoFinalPagadoChanging(System.Nullable<double> value);
    partial void OnsaldoFinalPagadoChanged();
    #endregion
		
		public PresupuestoGastos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPresupuesto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPresupuesto
		{
			get
			{
				return this._idPresupuesto;
			}
			set
			{
				if ((this._idPresupuesto != value))
				{
					this.OnidPresupuestoChanging(value);
					this.SendPropertyChanging();
					this._idPresupuesto = value;
					this.SendPropertyChanged("idPresupuesto");
					this.OnidPresupuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCuenta", DbType="Int")]
		public System.Nullable<int> idCuenta
		{
			get
			{
				return this._idCuenta;
			}
			set
			{
				if ((this._idCuenta != value))
				{
					this.OnidCuentaChanging(value);
					this.SendPropertyChanging();
					this._idCuenta = value;
					this.SendPropertyChanged("idCuenta");
					this.OnidCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPeriodo", DbType="Int")]
		public System.Nullable<int> idPeriodo
		{
			get
			{
				return this._idPeriodo;
			}
			set
			{
				if ((this._idPeriodo != value))
				{
					this.OnidPeriodoChanging(value);
					this.SendPropertyChanging();
					this._idPeriodo = value;
					this.SendPropertyChanged("idPeriodo");
					this.OnidPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoInicialAprobado", DbType="Float")]
		public System.Nullable<double> saldoInicialAprobado
		{
			get
			{
				return this._saldoInicialAprobado;
			}
			set
			{
				if ((this._saldoInicialAprobado != value))
				{
					this.OnsaldoInicialAprobadoChanging(value);
					this.SendPropertyChanging();
					this._saldoInicialAprobado = value;
					this.SendPropertyChanged("saldoInicialAprobado");
					this.OnsaldoInicialAprobadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoFinalAprobado", DbType="Float")]
		public System.Nullable<double> saldoFinalAprobado
		{
			get
			{
				return this._saldoFinalAprobado;
			}
			set
			{
				if ((this._saldoFinalAprobado != value))
				{
					this.OnsaldoFinalAprobadoChanging(value);
					this.SendPropertyChanging();
					this._saldoFinalAprobado = value;
					this.SendPropertyChanged("saldoFinalAprobado");
					this.OnsaldoFinalAprobadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoInicialXEjercer", DbType="Float")]
		public System.Nullable<double> saldoInicialXEjercer
		{
			get
			{
				return this._saldoInicialXEjercer;
			}
			set
			{
				if ((this._saldoInicialXEjercer != value))
				{
					this.OnsaldoInicialXEjercerChanging(value);
					this.SendPropertyChanging();
					this._saldoInicialXEjercer = value;
					this.SendPropertyChanged("saldoInicialXEjercer");
					this.OnsaldoInicialXEjercerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoFinalXEjercer", DbType="Float")]
		public System.Nullable<double> saldoFinalXEjercer
		{
			get
			{
				return this._saldoFinalXEjercer;
			}
			set
			{
				if ((this._saldoFinalXEjercer != value))
				{
					this.OnsaldoFinalXEjercerChanging(value);
					this.SendPropertyChanging();
					this._saldoFinalXEjercer = value;
					this.SendPropertyChanged("saldoFinalXEjercer");
					this.OnsaldoFinalXEjercerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoInicialModificado", DbType="Float")]
		public System.Nullable<double> saldoInicialModificado
		{
			get
			{
				return this._saldoInicialModificado;
			}
			set
			{
				if ((this._saldoInicialModificado != value))
				{
					this.OnsaldoInicialModificadoChanging(value);
					this.SendPropertyChanging();
					this._saldoInicialModificado = value;
					this.SendPropertyChanged("saldoInicialModificado");
					this.OnsaldoInicialModificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoFinalModificado", DbType="Float")]
		public System.Nullable<double> saldoFinalModificado
		{
			get
			{
				return this._saldoFinalModificado;
			}
			set
			{
				if ((this._saldoFinalModificado != value))
				{
					this.OnsaldoFinalModificadoChanging(value);
					this.SendPropertyChanging();
					this._saldoFinalModificado = value;
					this.SendPropertyChanged("saldoFinalModificado");
					this.OnsaldoFinalModificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoInicialComprometido", DbType="Float")]
		public System.Nullable<double> saldoInicialComprometido
		{
			get
			{
				return this._saldoInicialComprometido;
			}
			set
			{
				if ((this._saldoInicialComprometido != value))
				{
					this.OnsaldoInicialComprometidoChanging(value);
					this.SendPropertyChanging();
					this._saldoInicialComprometido = value;
					this.SendPropertyChanged("saldoInicialComprometido");
					this.OnsaldoInicialComprometidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoFinalComprometido", DbType="Float")]
		public System.Nullable<double> saldoFinalComprometido
		{
			get
			{
				return this._saldoFinalComprometido;
			}
			set
			{
				if ((this._saldoFinalComprometido != value))
				{
					this.OnsaldoFinalComprometidoChanging(value);
					this.SendPropertyChanging();
					this._saldoFinalComprometido = value;
					this.SendPropertyChanged("saldoFinalComprometido");
					this.OnsaldoFinalComprometidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoInicalDevengado", DbType="Float")]
		public System.Nullable<double> saldoInicalDevengado
		{
			get
			{
				return this._saldoInicalDevengado;
			}
			set
			{
				if ((this._saldoInicalDevengado != value))
				{
					this.OnsaldoInicalDevengadoChanging(value);
					this.SendPropertyChanging();
					this._saldoInicalDevengado = value;
					this.SendPropertyChanged("saldoInicalDevengado");
					this.OnsaldoInicalDevengadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoFinalDevengado", DbType="Float")]
		public System.Nullable<double> saldoFinalDevengado
		{
			get
			{
				return this._saldoFinalDevengado;
			}
			set
			{
				if ((this._saldoFinalDevengado != value))
				{
					this.OnsaldoFinalDevengadoChanging(value);
					this.SendPropertyChanging();
					this._saldoFinalDevengado = value;
					this.SendPropertyChanged("saldoFinalDevengado");
					this.OnsaldoFinalDevengadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoInicialEjercido", DbType="Float")]
		public System.Nullable<double> saldoInicialEjercido
		{
			get
			{
				return this._saldoInicialEjercido;
			}
			set
			{
				if ((this._saldoInicialEjercido != value))
				{
					this.OnsaldoInicialEjercidoChanging(value);
					this.SendPropertyChanging();
					this._saldoInicialEjercido = value;
					this.SendPropertyChanged("saldoInicialEjercido");
					this.OnsaldoInicialEjercidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoFinalEjercido", DbType="Float")]
		public System.Nullable<double> saldoFinalEjercido
		{
			get
			{
				return this._saldoFinalEjercido;
			}
			set
			{
				if ((this._saldoFinalEjercido != value))
				{
					this.OnsaldoFinalEjercidoChanging(value);
					this.SendPropertyChanging();
					this._saldoFinalEjercido = value;
					this.SendPropertyChanged("saldoFinalEjercido");
					this.OnsaldoFinalEjercidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoInicialPagado", DbType="Float")]
		public System.Nullable<double> saldoInicialPagado
		{
			get
			{
				return this._saldoInicialPagado;
			}
			set
			{
				if ((this._saldoInicialPagado != value))
				{
					this.OnsaldoInicialPagadoChanging(value);
					this.SendPropertyChanging();
					this._saldoInicialPagado = value;
					this.SendPropertyChanged("saldoInicialPagado");
					this.OnsaldoInicialPagadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoFinalPagado", DbType="Float")]
		public System.Nullable<double> saldoFinalPagado
		{
			get
			{
				return this._saldoFinalPagado;
			}
			set
			{
				if ((this._saldoFinalPagado != value))
				{
					this.OnsaldoFinalPagadoChanging(value);
					this.SendPropertyChanging();
					this._saldoFinalPagado = value;
					this.SendPropertyChanged("saldoFinalPagado");
					this.OnsaldoFinalPagadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CuentaEnc")]
	public partial class CuentaEnc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCuenta;
		
		private string _Nombre;
		
		private string _Cuenta;
		
		private int _Padre;
		
		private char _TipoCuenta;
		
		private char _Hoja;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCuentaChanging(int value);
    partial void OnIdCuentaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCuentaChanging(string value);
    partial void OnCuentaChanged();
    partial void OnPadreChanging(int value);
    partial void OnPadreChanged();
    partial void OnTipoCuentaChanging(char value);
    partial void OnTipoCuentaChanged();
    partial void OnHojaChanging(char value);
    partial void OnHojaChanged();
    #endregion
		
		public CuentaEnc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCuenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCuenta
		{
			get
			{
				return this._IdCuenta;
			}
			set
			{
				if ((this._IdCuenta != value))
				{
					this.OnIdCuentaChanging(value);
					this.SendPropertyChanging();
					this._IdCuenta = value;
					this.SendPropertyChanged("IdCuenta");
					this.OnIdCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuenta", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Cuenta
		{
			get
			{
				return this._Cuenta;
			}
			set
			{
				if ((this._Cuenta != value))
				{
					this.OnCuentaChanging(value);
					this.SendPropertyChanging();
					this._Cuenta = value;
					this.SendPropertyChanged("Cuenta");
					this.OnCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Padre", DbType="Int NOT NULL")]
		public int Padre
		{
			get
			{
				return this._Padre;
			}
			set
			{
				if ((this._Padre != value))
				{
					this.OnPadreChanging(value);
					this.SendPropertyChanging();
					this._Padre = value;
					this.SendPropertyChanged("Padre");
					this.OnPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuenta", DbType="Char(1) NOT NULL")]
		public char TipoCuenta
		{
			get
			{
				return this._TipoCuenta;
			}
			set
			{
				if ((this._TipoCuenta != value))
				{
					this.OnTipoCuentaChanging(value);
					this.SendPropertyChanging();
					this._TipoCuenta = value;
					this.SendPropertyChanged("TipoCuenta");
					this.OnTipoCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoja", DbType="Char(1) NOT NULL")]
		public char Hoja
		{
			get
			{
				return this._Hoja;
			}
			set
			{
				if ((this._Hoja != value))
				{
					this.OnHojaChanging(value);
					this.SendPropertyChanging();
					this._Hoja = value;
					this.SendPropertyChanged("Hoja");
					this.OnHojaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
