#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SacIntegrado.Presupuesto
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sac")]
	public partial class ConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertRecurso(Recurso instance);
    partial void UpdateRecurso(Recurso instance);
    partial void DeleteRecurso(Recurso instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertActividadPoa(ActividadPoa instance);
    partial void UpdateActividadPoa(ActividadPoa instance);
    partial void DeleteActividadPoa(ActividadPoa instance);
    partial void InsertClasificadorProgramatico(ClasificadorProgramatico instance);
    partial void UpdateClasificadorProgramatico(ClasificadorProgramatico instance);
    partial void DeleteClasificadorProgramatico(ClasificadorProgramatico instance);
    partial void InsertCuentaEnc(CuentaEnc instance);
    partial void UpdateCuentaEnc(CuentaEnc instance);
    partial void DeleteCuentaEnc(CuentaEnc instance);
    partial void InsertPeriodo(Periodo instance);
    partial void UpdatePeriodo(Periodo instance);
    partial void DeletePeriodo(Periodo instance);
    partial void InsertPartidaProyecto(PartidaProyecto instance);
    partial void UpdatePartidaProyecto(PartidaProyecto instance);
    partial void DeletePartidaProyecto(PartidaProyecto instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    partial void InsertProyecto(Proyecto instance);
    partial void UpdateProyecto(Proyecto instance);
    partial void DeleteProyecto(Proyecto instance);
    #endregion
		
		public ConexionDataContext() : 
				base(global::SacIntegrado.Properties.Settings.Default.sacConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Recurso> Recurso
		{
			get
			{
				return this.GetTable<Recurso>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<ActividadPoa> ActividadPoa
		{
			get
			{
				return this.GetTable<ActividadPoa>();
			}
		}
		
		public System.Data.Linq.Table<ClasificadorFuncional> ClasificadorFuncional
		{
			get
			{
				return this.GetTable<ClasificadorFuncional>();
			}
		}
		
		public System.Data.Linq.Table<ClasificadorProgramatico> ClasificadorProgramatico
		{
			get
			{
				return this.GetTable<ClasificadorProgramatico>();
			}
		}
		
		public System.Data.Linq.Table<CuentaEnc> CuentaEnc
		{
			get
			{
				return this.GetTable<CuentaEnc>();
			}
		}
		
		public System.Data.Linq.Table<Periodo> Periodo
		{
			get
			{
				return this.GetTable<Periodo>();
			}
		}
		
		public System.Data.Linq.Table<PartidaProyecto> PartidaProyecto
		{
			get
			{
				return this.GetTable<PartidaProyecto>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamento
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Proyecto> Proyecto
		{
			get
			{
				return this.GetTable<Proyecto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recurso")]
	public partial class Recurso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRecurso;
		
		private string _Nombre;
		
		private System.Nullable<int> _ClavePresupuestal;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private System.Nullable<int> _AnioAplica;
		
		private System.Nullable<int> _idEmpleado;
		
		private System.Nullable<bool> _Vigente;
		
		private System.Nullable<double> _SaldoInicial;
		
		private System.Nullable<double> _SaldoFin;
		
		private string _Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRecursoChanging(int value);
    partial void OnidRecursoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnClavePresupuestalChanging(System.Nullable<int> value);
    partial void OnClavePresupuestalChanged();
    partial void OnFechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRegistroChanged();
    partial void OnAnioAplicaChanging(System.Nullable<int> value);
    partial void OnAnioAplicaChanged();
    partial void OnidEmpleadoChanging(System.Nullable<int> value);
    partial void OnidEmpleadoChanged();
    partial void OnVigenteChanging(System.Nullable<bool> value);
    partial void OnVigenteChanged();
    partial void OnSaldoInicialChanging(System.Nullable<double> value);
    partial void OnSaldoInicialChanged();
    partial void OnSaldoFinChanging(System.Nullable<double> value);
    partial void OnSaldoFinChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    #endregion
		
		public Recurso()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRecurso
		{
			get
			{
				return this._idRecurso;
			}
			set
			{
				if ((this._idRecurso != value))
				{
					this.OnidRecursoChanging(value);
					this.SendPropertyChanging();
					this._idRecurso = value;
					this.SendPropertyChanged("idRecurso");
					this.OnidRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClavePresupuestal", DbType="Int")]
		public System.Nullable<int> ClavePresupuestal
		{
			get
			{
				return this._ClavePresupuestal;
			}
			set
			{
				if ((this._ClavePresupuestal != value))
				{
					this.OnClavePresupuestalChanging(value);
					this.SendPropertyChanging();
					this._ClavePresupuestal = value;
					this.SendPropertyChanged("ClavePresupuestal");
					this.OnClavePresupuestalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="Date")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioAplica", DbType="Int")]
		public System.Nullable<int> AnioAplica
		{
			get
			{
				return this._AnioAplica;
			}
			set
			{
				if ((this._AnioAplica != value))
				{
					this.OnAnioAplicaChanging(value);
					this.SendPropertyChanging();
					this._AnioAplica = value;
					this.SendPropertyChanged("AnioAplica");
					this.OnAnioAplicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int")]
		public System.Nullable<int> idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vigente", DbType="Bit")]
		public System.Nullable<bool> Vigente
		{
			get
			{
				return this._Vigente;
			}
			set
			{
				if ((this._Vigente != value))
				{
					this.OnVigenteChanging(value);
					this.SendPropertyChanging();
					this._Vigente = value;
					this.SendPropertyChanged("Vigente");
					this.OnVigenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoInicial", DbType="Float")]
		public System.Nullable<double> SaldoInicial
		{
			get
			{
				return this._SaldoInicial;
			}
			set
			{
				if ((this._SaldoInicial != value))
				{
					this.OnSaldoInicialChanging(value);
					this.SendPropertyChanging();
					this._SaldoInicial = value;
					this.SendPropertyChanged("SaldoInicial");
					this.OnSaldoInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoFin", DbType="Float")]
		public System.Nullable<double> SaldoFin
		{
			get
			{
				return this._SaldoFin;
			}
			set
			{
				if ((this._SaldoFin != value))
				{
					this.OnSaldoFinChanging(value);
					this.SendPropertyChanging();
					this._SaldoFin = value;
					this.SendPropertyChanged("SaldoFin");
					this.OnSaldoFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(150)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmpleado;
		
		private string _Nombre;
		
		private System.Nullable<int> _idCategoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnidCategoriaChanging(System.Nullable<int> value);
    partial void OnidCategoriaChanged();
    #endregion
		
		public Empleado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int")]
		public System.Nullable<int> idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActividadPoa")]
	public partial class ActividadPoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _idActPoa;
		
		private string _Nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidActPoaChanging(System.Nullable<int> value);
    partial void OnidActPoaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public ActividadPoa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idActPoa", DbType="Int", IsPrimaryKey=true)]
		public System.Nullable<int> idActPoa
		{
			get
			{
				return this._idActPoa;
			}
			set
			{
				if ((this._idActPoa != value))
				{
					this.OnidActPoaChanging(value);
					this.SendPropertyChanging();
					this._idActPoa = value;
					this.SendPropertyChanged("idActPoa");
					this.OnidActPoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClasificadorFuncional")]
	public partial class ClasificadorFuncional
	{
		
		private int _idClasifFuncional;
		
		private string _Nombre;
		
		private string _Clave;
		
		private System.Nullable<int> _Anio;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _PersonaRegistro;
		
		private System.Nullable<bool> _vigente;
		
		public ClasificadorFuncional()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasifFuncional", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int idClasifFuncional
		{
			get
			{
				return this._idClasifFuncional;
			}
			set
			{
				if ((this._idClasifFuncional != value))
				{
					this._idClasifFuncional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(50)")]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this._Clave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anio", DbType="Int")]
		public System.Nullable<int> Anio
		{
			get
			{
				return this._Anio;
			}
			set
			{
				if ((this._Anio != value))
				{
					this._Anio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaRegistro", DbType="VarChar(50)")]
		public string PersonaRegistro
		{
			get
			{
				return this._PersonaRegistro;
			}
			set
			{
				if ((this._PersonaRegistro != value))
				{
					this._PersonaRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigente", DbType="Bit")]
		public System.Nullable<bool> vigente
		{
			get
			{
				return this._vigente;
			}
			set
			{
				if ((this._vigente != value))
				{
					this._vigente = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClasificadorProgramatico")]
	public partial class ClasificadorProgramatico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idClasificadorPro;
		
		private string _Nombre;
		
		private string _Clave;
		
		private System.Nullable<int> _anio;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _personaRegistro;
		
		private System.Nullable<bool> _vigente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClasificadorProChanging(int value);
    partial void OnidClasificadorProChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnanioChanging(System.Nullable<int> value);
    partial void OnanioChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnpersonaRegistroChanging(string value);
    partial void OnpersonaRegistroChanged();
    partial void OnvigenteChanging(System.Nullable<bool> value);
    partial void OnvigenteChanged();
    #endregion
		
		public ClasificadorProgramatico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasificadorPro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idClasificadorPro
		{
			get
			{
				return this._idClasificadorPro;
			}
			set
			{
				if ((this._idClasificadorPro != value))
				{
					this.OnidClasificadorProChanging(value);
					this.SendPropertyChanging();
					this._idClasificadorPro = value;
					this.SendPropertyChanged("idClasificadorPro");
					this.OnidClasificadorProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(50)")]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int")]
		public System.Nullable<int> anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this.OnanioChanging(value);
					this.SendPropertyChanging();
					this._anio = value;
					this.SendPropertyChanged("anio");
					this.OnanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personaRegistro", DbType="VarChar(50)")]
		public string personaRegistro
		{
			get
			{
				return this._personaRegistro;
			}
			set
			{
				if ((this._personaRegistro != value))
				{
					this.OnpersonaRegistroChanging(value);
					this.SendPropertyChanging();
					this._personaRegistro = value;
					this.SendPropertyChanged("personaRegistro");
					this.OnpersonaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigente", DbType="Bit")]
		public System.Nullable<bool> vigente
		{
			get
			{
				return this._vigente;
			}
			set
			{
				if ((this._vigente != value))
				{
					this.OnvigenteChanging(value);
					this.SendPropertyChanging();
					this._vigente = value;
					this.SendPropertyChanged("vigente");
					this.OnvigenteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CuentaEnc")]
	public partial class CuentaEnc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCuenta;
		
		private string _Cuenta;
		
		private string _Nombre;
		
		private System.Nullable<int> _Padre;
		
		private System.Nullable<char> _TipoCuenta;
		
		private System.Nullable<char> _Hoja;
		
		private System.Nullable<bool> _Status;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCuentaChanging(int value);
    partial void OnIdCuentaChanged();
    partial void OnCuentaChanging(string value);
    partial void OnCuentaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPadreChanging(System.Nullable<int> value);
    partial void OnPadreChanged();
    partial void OnTipoCuentaChanging(System.Nullable<char> value);
    partial void OnTipoCuentaChanged();
    partial void OnHojaChanging(System.Nullable<char> value);
    partial void OnHojaChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public CuentaEnc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCuenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCuenta
		{
			get
			{
				return this._IdCuenta;
			}
			set
			{
				if ((this._IdCuenta != value))
				{
					this.OnIdCuentaChanging(value);
					this.SendPropertyChanging();
					this._IdCuenta = value;
					this.SendPropertyChanged("IdCuenta");
					this.OnIdCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuenta", DbType="Char(10)")]
		public string Cuenta
		{
			get
			{
				return this._Cuenta;
			}
			set
			{
				if ((this._Cuenta != value))
				{
					this.OnCuentaChanging(value);
					this.SendPropertyChanging();
					this._Cuenta = value;
					this.SendPropertyChanged("Cuenta");
					this.OnCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Padre", DbType="Int")]
		public System.Nullable<int> Padre
		{
			get
			{
				return this._Padre;
			}
			set
			{
				if ((this._Padre != value))
				{
					this.OnPadreChanging(value);
					this.SendPropertyChanging();
					this._Padre = value;
					this.SendPropertyChanged("Padre");
					this.OnPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuenta", DbType="Char(1)")]
		public System.Nullable<char> TipoCuenta
		{
			get
			{
				return this._TipoCuenta;
			}
			set
			{
				if ((this._TipoCuenta != value))
				{
					this.OnTipoCuentaChanging(value);
					this.SendPropertyChanging();
					this._TipoCuenta = value;
					this.SendPropertyChanged("TipoCuenta");
					this.OnTipoCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoja", DbType="Char(1)")]
		public System.Nullable<char> Hoja
		{
			get
			{
				return this._Hoja;
			}
			set
			{
				if ((this._Hoja != value))
				{
					this.OnHojaChanging(value);
					this.SendPropertyChanging();
					this._Hoja = value;
					this.SendPropertyChanged("Hoja");
					this.OnHojaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Periodo")]
	public partial class Periodo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPeriodo;
		
		private System.Nullable<int> _mes;
		
		private System.Nullable<int> _anio;
		
		private System.Nullable<char> _status;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPeriodoChanging(int value);
    partial void OnidPeriodoChanged();
    partial void OnmesChanging(System.Nullable<int> value);
    partial void OnmesChanged();
    partial void OnanioChanging(System.Nullable<int> value);
    partial void OnanioChanged();
    partial void OnstatusChanging(System.Nullable<char> value);
    partial void OnstatusChanged();
    #endregion
		
		public Periodo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPeriodo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPeriodo
		{
			get
			{
				return this._idPeriodo;
			}
			set
			{
				if ((this._idPeriodo != value))
				{
					this.OnidPeriodoChanging(value);
					this.SendPropertyChanging();
					this._idPeriodo = value;
					this.SendPropertyChanged("idPeriodo");
					this.OnidPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mes", DbType="Int")]
		public System.Nullable<int> mes
		{
			get
			{
				return this._mes;
			}
			set
			{
				if ((this._mes != value))
				{
					this.OnmesChanging(value);
					this.SendPropertyChanging();
					this._mes = value;
					this.SendPropertyChanged("mes");
					this.OnmesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int")]
		public System.Nullable<int> anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this.OnanioChanging(value);
					this.SendPropertyChanging();
					this._anio = value;
					this.SendPropertyChanged("anio");
					this.OnanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(1)")]
		public System.Nullable<char> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PartidaProyecto")]
	public partial class PartidaProyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCtaProy;
		
		private System.Nullable<int> _idCuenta;
		
		private System.Nullable<int> _idProyecto;
		
		private System.Nullable<int> _idPeriodo;
		
		private System.Nullable<double> _saldoInicial;
		
		private System.Nullable<double> _saldoFin;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCtaProyChanging(int value);
    partial void OnidCtaProyChanged();
    partial void OnidCuentaChanging(System.Nullable<int> value);
    partial void OnidCuentaChanged();
    partial void OnidProyectoChanging(System.Nullable<int> value);
    partial void OnidProyectoChanged();
    partial void OnidPeriodoChanging(System.Nullable<int> value);
    partial void OnidPeriodoChanged();
    partial void OnsaldoInicialChanging(System.Nullable<double> value);
    partial void OnsaldoInicialChanged();
    partial void OnsaldoFinChanging(System.Nullable<double> value);
    partial void OnsaldoFinChanged();
    #endregion
		
		public PartidaProyecto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCtaProy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCtaProy
		{
			get
			{
				return this._idCtaProy;
			}
			set
			{
				if ((this._idCtaProy != value))
				{
					this.OnidCtaProyChanging(value);
					this.SendPropertyChanging();
					this._idCtaProy = value;
					this.SendPropertyChanged("idCtaProy");
					this.OnidCtaProyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCuenta", DbType="Int")]
		public System.Nullable<int> idCuenta
		{
			get
			{
				return this._idCuenta;
			}
			set
			{
				if ((this._idCuenta != value))
				{
					this.OnidCuentaChanging(value);
					this.SendPropertyChanging();
					this._idCuenta = value;
					this.SendPropertyChanged("idCuenta");
					this.OnidCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProyecto", DbType="Int")]
		public System.Nullable<int> idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				if ((this._idProyecto != value))
				{
					this.OnidProyectoChanging(value);
					this.SendPropertyChanging();
					this._idProyecto = value;
					this.SendPropertyChanged("idProyecto");
					this.OnidProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPeriodo", DbType="Int")]
		public System.Nullable<int> idPeriodo
		{
			get
			{
				return this._idPeriodo;
			}
			set
			{
				if ((this._idPeriodo != value))
				{
					this.OnidPeriodoChanging(value);
					this.SendPropertyChanging();
					this._idPeriodo = value;
					this.SendPropertyChanged("idPeriodo");
					this.OnidPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoInicial", DbType="Float")]
		public System.Nullable<double> saldoInicial
		{
			get
			{
				return this._saldoInicial;
			}
			set
			{
				if ((this._saldoInicial != value))
				{
					this.OnsaldoInicialChanging(value);
					this.SendPropertyChanging();
					this._saldoInicial = value;
					this.SendPropertyChanged("saldoInicial");
					this.OnsaldoInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoFin", DbType="Float")]
		public System.Nullable<double> saldoFin
		{
			get
			{
				return this._saldoFin;
			}
			set
			{
				if ((this._saldoFin != value))
				{
					this.OnsaldoFinChanging(value);
					this.SendPropertyChanging();
					this._saldoFin = value;
					this.SendPropertyChanged("saldoFin");
					this.OnsaldoFinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDepto;
		
		private string _NombreDepto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDeptoChanging(int value);
    partial void OnidDeptoChanged();
    partial void OnNombreDeptoChanging(string value);
    partial void OnNombreDeptoChanged();
    #endregion
		
		public Departamento()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDepto
		{
			get
			{
				return this._idDepto;
			}
			set
			{
				if ((this._idDepto != value))
				{
					this.OnidDeptoChanging(value);
					this.SendPropertyChanging();
					this._idDepto = value;
					this.SendPropertyChanged("idDepto");
					this.OnidDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDepto", DbType="VarChar(90)")]
		public string NombreDepto
		{
			get
			{
				return this._NombreDepto;
			}
			set
			{
				if ((this._NombreDepto != value))
				{
					this.OnNombreDeptoChanging(value);
					this.SendPropertyChanging();
					this._NombreDepto = value;
					this.SendPropertyChanged("NombreDepto");
					this.OnNombreDeptoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proyecto")]
	public partial class Proyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProyecto;
		
		private string _Nombre;
		
		private System.Nullable<int> _idResponsable;
		
		private System.Nullable<int> _idRecurso;
		
		private System.Nullable<int> _idsOtrosClasificadores;
		
		private System.Nullable<int> _idDepto;
		
		private System.Nullable<int> _idActPoa;
		
		private System.Nullable<int> _idClasifFuncional;
		
		private System.Nullable<int> _idClasifProgramatico;
		
		private System.Nullable<int> _anioAplica;
		
		private string _justificacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProyectoChanging(int value);
    partial void OnidProyectoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnidResponsableChanging(System.Nullable<int> value);
    partial void OnidResponsableChanged();
    partial void OnidRecursoChanging(System.Nullable<int> value);
    partial void OnidRecursoChanged();
    partial void OnidsOtrosClasificadoresChanging(System.Nullable<int> value);
    partial void OnidsOtrosClasificadoresChanged();
    partial void OnidDeptoChanging(System.Nullable<int> value);
    partial void OnidDeptoChanged();
    partial void OnidActPoaChanging(System.Nullable<int> value);
    partial void OnidActPoaChanged();
    partial void OnidClasifFuncionalChanging(System.Nullable<int> value);
    partial void OnidClasifFuncionalChanged();
    partial void OnidClasifProgramaticoChanging(System.Nullable<int> value);
    partial void OnidClasifProgramaticoChanged();
    partial void OnanioAplicaChanging(System.Nullable<int> value);
    partial void OnanioAplicaChanged();
    partial void OnjustificacionChanging(string value);
    partial void OnjustificacionChanged();
    #endregion
		
		public Proyecto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProyecto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				if ((this._idProyecto != value))
				{
					this.OnidProyectoChanging(value);
					this.SendPropertyChanging();
					this._idProyecto = value;
					this.SendPropertyChanged("idProyecto");
					this.OnidProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idResponsable", DbType="Int")]
		public System.Nullable<int> idResponsable
		{
			get
			{
				return this._idResponsable;
			}
			set
			{
				if ((this._idResponsable != value))
				{
					this.OnidResponsableChanging(value);
					this.SendPropertyChanging();
					this._idResponsable = value;
					this.SendPropertyChanged("idResponsable");
					this.OnidResponsableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecurso", DbType="Int")]
		public System.Nullable<int> idRecurso
		{
			get
			{
				return this._idRecurso;
			}
			set
			{
				if ((this._idRecurso != value))
				{
					this.OnidRecursoChanging(value);
					this.SendPropertyChanging();
					this._idRecurso = value;
					this.SendPropertyChanged("idRecurso");
					this.OnidRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsOtrosClasificadores", DbType="Int")]
		public System.Nullable<int> idsOtrosClasificadores
		{
			get
			{
				return this._idsOtrosClasificadores;
			}
			set
			{
				if ((this._idsOtrosClasificadores != value))
				{
					this.OnidsOtrosClasificadoresChanging(value);
					this.SendPropertyChanging();
					this._idsOtrosClasificadores = value;
					this.SendPropertyChanged("idsOtrosClasificadores");
					this.OnidsOtrosClasificadoresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepto", DbType="Int")]
		public System.Nullable<int> idDepto
		{
			get
			{
				return this._idDepto;
			}
			set
			{
				if ((this._idDepto != value))
				{
					this.OnidDeptoChanging(value);
					this.SendPropertyChanging();
					this._idDepto = value;
					this.SendPropertyChanged("idDepto");
					this.OnidDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idActPoa", DbType="Int")]
		public System.Nullable<int> idActPoa
		{
			get
			{
				return this._idActPoa;
			}
			set
			{
				if ((this._idActPoa != value))
				{
					this.OnidActPoaChanging(value);
					this.SendPropertyChanging();
					this._idActPoa = value;
					this.SendPropertyChanged("idActPoa");
					this.OnidActPoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasifFuncional", DbType="Int")]
		public System.Nullable<int> idClasifFuncional
		{
			get
			{
				return this._idClasifFuncional;
			}
			set
			{
				if ((this._idClasifFuncional != value))
				{
					this.OnidClasifFuncionalChanging(value);
					this.SendPropertyChanging();
					this._idClasifFuncional = value;
					this.SendPropertyChanged("idClasifFuncional");
					this.OnidClasifFuncionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasifProgramatico", DbType="Int")]
		public System.Nullable<int> idClasifProgramatico
		{
			get
			{
				return this._idClasifProgramatico;
			}
			set
			{
				if ((this._idClasifProgramatico != value))
				{
					this.OnidClasifProgramaticoChanging(value);
					this.SendPropertyChanging();
					this._idClasifProgramatico = value;
					this.SendPropertyChanged("idClasifProgramatico");
					this.OnidClasifProgramaticoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anioAplica", DbType="Int")]
		public System.Nullable<int> anioAplica
		{
			get
			{
				return this._anioAplica;
			}
			set
			{
				if ((this._anioAplica != value))
				{
					this.OnanioAplicaChanging(value);
					this.SendPropertyChanging();
					this._anioAplica = value;
					this.SendPropertyChanged("anioAplica");
					this.OnanioAplicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_justificacion", DbType="VarChar(100)")]
		public string justificacion
		{
			get
			{
				return this._justificacion;
			}
			set
			{
				if ((this._justificacion != value))
				{
					this.OnjustificacionChanging(value);
					this.SendPropertyChanging();
					this._justificacion = value;
					this.SendPropertyChanged("justificacion");
					this.OnjustificacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
