#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SacIntegrado.Presupuesto
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sac")]
	public partial class pruebaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertClasificadorFunc(ClasificadorFunc instance);
    partial void UpdateClasificadorFunc(ClasificadorFunc instance);
    partial void DeleteClasificadorFunc(ClasificadorFunc instance);
    partial void InsertClasificadorProg(ClasificadorProg instance);
    partial void UpdateClasificadorProg(ClasificadorProg instance);
    partial void DeleteClasificadorProg(ClasificadorProg instance);
    #endregion
		
		public pruebaDataContext() : 
				base(global::SacIntegrado.Properties.Settings.Default.sacConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pruebaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pruebaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pruebaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pruebaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<ClasificadorFunc> ClasificadorFunc
		{
			get
			{
				return this.GetTable<ClasificadorFunc>();
			}
		}
		
		public System.Data.Linq.Table<ClasificadorProg> ClasificadorProg
		{
			get
			{
				return this.GetTable<ClasificadorProg>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios
	{
		
		private int _idUsuario;
		
		private string _nombre;
		
		private string _email;
		
		private string _nick;
		
		private string _password;
		
		public Usuarios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(10)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nick", DbType="VarChar(50)")]
		public string nick
		{
			get
			{
				return this._nick;
			}
			set
			{
				if ((this._nick != value))
				{
					this._nick = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(15)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClasificadorFuncional")]
	public partial class ClasificadorFunc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idClasifFuncional;
		
		private string _Nombre;
		
		private string _clave;
		
		private System.Nullable<int> _anio;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _personaRegistro;
		
		private System.Nullable<bool> _vigente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClasifFuncionalChanging(int value);
    partial void OnidClasifFuncionalChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnanioChanging(System.Nullable<int> value);
    partial void OnanioChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnpersonaRegistroChanging(string value);
    partial void OnpersonaRegistroChanged();
    partial void OnvigenteChanging(System.Nullable<bool> value);
    partial void OnvigenteChanged();
    #endregion
		
		public ClasificadorFunc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasifFuncional", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idClasifFuncional
		{
			get
			{
				return this._idClasifFuncional;
			}
			set
			{
				if ((this._idClasifFuncional != value))
				{
					this.OnidClasifFuncionalChanging(value);
					this.SendPropertyChanging();
					this._idClasifFuncional = value;
					this.SendPropertyChanged("idClasifFuncional");
					this.OnidClasifFuncionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(50)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int")]
		public System.Nullable<int> anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this.OnanioChanging(value);
					this.SendPropertyChanging();
					this._anio = value;
					this.SendPropertyChanged("anio");
					this.OnanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personaRegistro", DbType="VarChar(70)")]
		public string personaRegistro
		{
			get
			{
				return this._personaRegistro;
			}
			set
			{
				if ((this._personaRegistro != value))
				{
					this.OnpersonaRegistroChanging(value);
					this.SendPropertyChanging();
					this._personaRegistro = value;
					this.SendPropertyChanged("personaRegistro");
					this.OnpersonaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigente", DbType="Bit")]
		public System.Nullable<bool> vigente
		{
			get
			{
				return this._vigente;
			}
			set
			{
				if ((this._vigente != value))
				{
					this.OnvigenteChanging(value);
					this.SendPropertyChanging();
					this._vigente = value;
					this.SendPropertyChanged("vigente");
					this.OnvigenteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClasificadorProg")]
	public partial class ClasificadorProg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idClasificadorPro;
		
		private string _Nombre;
		
		private string _clave;
		
		private System.Nullable<int> _anio;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _personaRegistro;
		
		private System.Nullable<bool> _vigente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClasificadorProChanging(int value);
    partial void OnidClasificadorProChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnanioChanging(System.Nullable<int> value);
    partial void OnanioChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnpersonaRegistroChanging(string value);
    partial void OnpersonaRegistroChanged();
    partial void OnvigenteChanging(System.Nullable<bool> value);
    partial void OnvigenteChanged();
    #endregion
		
		public ClasificadorProg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasificadorPro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idClasificadorPro
		{
			get
			{
				return this._idClasificadorPro;
			}
			set
			{
				if ((this._idClasificadorPro != value))
				{
					this.OnidClasificadorProChanging(value);
					this.SendPropertyChanging();
					this._idClasificadorPro = value;
					this.SendPropertyChanged("idClasificadorPro");
					this.OnidClasificadorProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(50)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int")]
		public System.Nullable<int> anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this.OnanioChanging(value);
					this.SendPropertyChanging();
					this._anio = value;
					this.SendPropertyChanged("anio");
					this.OnanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personaRegistro", DbType="VarChar(70)")]
		public string personaRegistro
		{
			get
			{
				return this._personaRegistro;
			}
			set
			{
				if ((this._personaRegistro != value))
				{
					this.OnpersonaRegistroChanging(value);
					this.SendPropertyChanging();
					this._personaRegistro = value;
					this.SendPropertyChanged("personaRegistro");
					this.OnpersonaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigente", DbType="Bit")]
		public System.Nullable<bool> vigente
		{
			get
			{
				return this._vigente;
			}
			set
			{
				if ((this._vigente != value))
				{
					this.OnvigenteChanging(value);
					this.SendPropertyChanging();
					this._vigente = value;
					this.SendPropertyChanged("vigente");
					this.OnvigenteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
