#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SacIntegrado.Adquisiciones
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sac")]
	public partial class ConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertProyecto(Proyecto instance);
    partial void UpdateProyecto(Proyecto instance);
    partial void DeleteProyecto(Proyecto instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertRequiEnc(RequiEnc instance);
    partial void UpdateRequiEnc(RequiEnc instance);
    partial void DeleteRequiEnc(RequiEnc instance);
    partial void InsertRequiDet(RequiDet instance);
    partial void UpdateRequiDet(RequiDet instance);
    partial void DeleteRequiDet(RequiDet instance);
    partial void InsertComprador(Comprador instance);
    partial void UpdateComprador(Comprador instance);
    partial void DeleteComprador(Comprador instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    #endregion
		
		public ConexionDataContext() : 
				base(global::SacIntegrado.Properties.Settings.Default.sacConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Proyecto> Proyecto
		{
			get
			{
				return this.GetTable<Proyecto>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<RequiEnc> RequiEnc
		{
			get
			{
				return this.GetTable<RequiEnc>();
			}
		}
		
		public System.Data.Linq.Table<RequiDet> RequiDet
		{
			get
			{
				return this.GetTable<RequiDet>();
			}
		}
		
		public System.Data.Linq.Table<Comprador> Comprador
		{
			get
			{
				return this.GetTable<Comprador>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamento
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proyecto")]
	public partial class Proyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProyecto;
		
		private string _Nombre;
		
		private System.Nullable<int> _idResponsable;
		
		private System.Nullable<int> _idRecurso;
		
		private System.Nullable<int> _idDepto;
		
		private EntitySet<RequiEnc> _RequiEnc;
		
		private EntityRef<Departamento> _Departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProyectoChanging(int value);
    partial void OnidProyectoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnidResponsableChanging(System.Nullable<int> value);
    partial void OnidResponsableChanged();
    partial void OnidRecursoChanging(System.Nullable<int> value);
    partial void OnidRecursoChanged();
    partial void OnidDeptoChanging(System.Nullable<int> value);
    partial void OnidDeptoChanged();
    #endregion
		
		public Proyecto()
		{
			this._RequiEnc = new EntitySet<RequiEnc>(new Action<RequiEnc>(this.attach_RequiEnc), new Action<RequiEnc>(this.detach_RequiEnc));
			this._Departamento = default(EntityRef<Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProyecto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				if ((this._idProyecto != value))
				{
					this.OnidProyectoChanging(value);
					this.SendPropertyChanging();
					this._idProyecto = value;
					this.SendPropertyChanged("idProyecto");
					this.OnidProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idResponsable", DbType="Int")]
		public System.Nullable<int> idResponsable
		{
			get
			{
				return this._idResponsable;
			}
			set
			{
				if ((this._idResponsable != value))
				{
					this.OnidResponsableChanging(value);
					this.SendPropertyChanging();
					this._idResponsable = value;
					this.SendPropertyChanged("idResponsable");
					this.OnidResponsableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecurso", DbType="Int")]
		public System.Nullable<int> idRecurso
		{
			get
			{
				return this._idRecurso;
			}
			set
			{
				if ((this._idRecurso != value))
				{
					this.OnidRecursoChanging(value);
					this.SendPropertyChanging();
					this._idRecurso = value;
					this.SendPropertyChanged("idRecurso");
					this.OnidRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepto", DbType="Int")]
		public System.Nullable<int> idDepto
		{
			get
			{
				return this._idDepto;
			}
			set
			{
				if ((this._idDepto != value))
				{
					if (this._Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDeptoChanging(value);
					this.SendPropertyChanging();
					this._idDepto = value;
					this.SendPropertyChanged("idDepto");
					this.OnidDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_RequiEnc", Storage="_RequiEnc", ThisKey="idProyecto", OtherKey="idProyecto")]
		public EntitySet<RequiEnc> RequiEnc
		{
			get
			{
				return this._RequiEnc;
			}
			set
			{
				this._RequiEnc.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Proyecto", Storage="_Departamento", ThisKey="idDepto", OtherKey="idDepto", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Proyecto.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Proyecto.Add(this);
						this._idDepto = value.idDepto;
					}
					else
					{
						this._idDepto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RequiEnc(RequiEnc entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = this;
		}
		
		private void detach_RequiEnc(RequiEnc entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProducto;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _unidadMed;
		
		private System.Nullable<double> _Costo;
		
		private System.Nullable<int> _idCuenta;
		
		private System.Nullable<int> _idClasificador;
		
		private System.Nullable<int> _idProveedor;
		
		private System.Nullable<int> _idCategoria;
		
		private EntitySet<RequiDet> _RequiDet;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductoChanging(int value);
    partial void OnidProductoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnunidadMedChanging(string value);
    partial void OnunidadMedChanged();
    partial void OnCostoChanging(System.Nullable<double> value);
    partial void OnCostoChanged();
    partial void OnidCuentaChanging(System.Nullable<int> value);
    partial void OnidCuentaChanged();
    partial void OnidClasificadorChanging(System.Nullable<int> value);
    partial void OnidClasificadorChanged();
    partial void OnidProveedorChanging(System.Nullable<int> value);
    partial void OnidProveedorChanged();
    partial void OnidCategoriaChanging(System.Nullable<int> value);
    partial void OnidCategoriaChanged();
    #endregion
		
		public Producto()
		{
			this._RequiDet = new EntitySet<RequiDet>(new Action<RequiDet>(this.attach_RequiDet), new Action<RequiDet>(this.detach_RequiDet));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this.OnidProductoChanging(value);
					this.SendPropertyChanging();
					this._idProducto = value;
					this.SendPropertyChanged("idProducto");
					this.OnidProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(80)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidadMed", DbType="VarChar(15)")]
		public string unidadMed
		{
			get
			{
				return this._unidadMed;
			}
			set
			{
				if ((this._unidadMed != value))
				{
					this.OnunidadMedChanging(value);
					this.SendPropertyChanging();
					this._unidadMed = value;
					this.SendPropertyChanged("unidadMed");
					this.OnunidadMedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Float")]
		public System.Nullable<double> Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this.OnCostoChanging(value);
					this.SendPropertyChanging();
					this._Costo = value;
					this.SendPropertyChanged("Costo");
					this.OnCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCuenta", DbType="Int")]
		public System.Nullable<int> idCuenta
		{
			get
			{
				return this._idCuenta;
			}
			set
			{
				if ((this._idCuenta != value))
				{
					this.OnidCuentaChanging(value);
					this.SendPropertyChanging();
					this._idCuenta = value;
					this.SendPropertyChanged("idCuenta");
					this.OnidCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasificador", DbType="Int")]
		public System.Nullable<int> idClasificador
		{
			get
			{
				return this._idClasificador;
			}
			set
			{
				if ((this._idClasificador != value))
				{
					this.OnidClasificadorChanging(value);
					this.SendPropertyChanging();
					this._idClasificador = value;
					this.SendPropertyChanged("idClasificador");
					this.OnidClasificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProveedor", DbType="Int")]
		public System.Nullable<int> idProveedor
		{
			get
			{
				return this._idProveedor;
			}
			set
			{
				if ((this._idProveedor != value))
				{
					this.OnidProveedorChanging(value);
					this.SendPropertyChanging();
					this._idProveedor = value;
					this.SendPropertyChanged("idProveedor");
					this.OnidProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int")]
		public System.Nullable<int> idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_RequiDet", Storage="_RequiDet", ThisKey="idProducto", OtherKey="idProducto")]
		public EntitySet<RequiDet> RequiDet
		{
			get
			{
				return this._RequiDet;
			}
			set
			{
				this._RequiDet.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RequiDet(RequiDet entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_RequiDet(RequiDet entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RequiEnc")]
	public partial class RequiEnc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRequisicion;
		
		private int _Folio;
		
		private System.Nullable<int> _idProyecto;
		
		private System.Nullable<int> _idEmpleado;
		
		private System.Nullable<System.DateTime> _fechaElaboracion;
		
		private System.Nullable<double> _importe;
		
		private string _Motivo;
		
		private string _Observaciones;
		
		private System.Nullable<System.DateTime> _FechaRequerida;
		
		private string _ArchivoSoporte;
		
		private System.Nullable<int> _statusRP;
		
		private System.Nullable<int> _statusJA;
		
		private System.Nullable<int> _statusJAC;
		
		private System.Nullable<int> _statusCO;
		
		private System.Nullable<int> _statusPresup;
		
		private System.Nullable<int> _idComprador;
		
		private EntitySet<RequiDet> _RequiDet;
		
		private EntityRef<Proyecto> _Proyecto;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRequisicionChanging(int value);
    partial void OnidRequisicionChanged();
    partial void OnFolioChanging(int value);
    partial void OnFolioChanged();
    partial void OnidProyectoChanging(System.Nullable<int> value);
    partial void OnidProyectoChanged();
    partial void OnidEmpleadoChanging(System.Nullable<int> value);
    partial void OnidEmpleadoChanged();
    partial void OnfechaElaboracionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaElaboracionChanged();
    partial void OnimporteChanging(System.Nullable<double> value);
    partial void OnimporteChanged();
    partial void OnMotivoChanging(string value);
    partial void OnMotivoChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    partial void OnFechaRequeridaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRequeridaChanged();
    partial void OnArchivoSoporteChanging(string value);
    partial void OnArchivoSoporteChanged();
    partial void OnstatusRPChanging(System.Nullable<int> value);
    partial void OnstatusRPChanged();
    partial void OnstatusJAChanging(System.Nullable<int> value);
    partial void OnstatusJAChanged();
    partial void OnstatusJACChanging(System.Nullable<int> value);
    partial void OnstatusJACChanged();
    partial void OnstatusCOChanging(System.Nullable<int> value);
    partial void OnstatusCOChanged();
    partial void OnstatusPresupChanging(System.Nullable<int> value);
    partial void OnstatusPresupChanged();
    partial void OnidCompradorChanging(System.Nullable<int> value);
    partial void OnidCompradorChanged();
    #endregion
		
		public RequiEnc()
		{
			this._RequiDet = new EntitySet<RequiDet>(new Action<RequiDet>(this.attach_RequiDet), new Action<RequiDet>(this.detach_RequiDet));
			this._Proyecto = default(EntityRef<Proyecto>);
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRequisicion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRequisicion
		{
			get
			{
				return this._idRequisicion;
			}
			set
			{
				if ((this._idRequisicion != value))
				{
					this.OnidRequisicionChanging(value);
					this.SendPropertyChanging();
					this._idRequisicion = value;
					this.SendPropertyChanged("idRequisicion");
					this.OnidRequisicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folio", DbType="Int NOT NULL")]
		public int Folio
		{
			get
			{
				return this._Folio;
			}
			set
			{
				if ((this._Folio != value))
				{
					this.OnFolioChanging(value);
					this.SendPropertyChanging();
					this._Folio = value;
					this.SendPropertyChanged("Folio");
					this.OnFolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProyecto", DbType="Int")]
		public System.Nullable<int> idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				if ((this._idProyecto != value))
				{
					if (this._Proyecto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProyectoChanging(value);
					this.SendPropertyChanging();
					this._idProyecto = value;
					this.SendPropertyChanged("idProyecto");
					this.OnidProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int")]
		public System.Nullable<int> idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaElaboracion", DbType="Date")]
		public System.Nullable<System.DateTime> fechaElaboracion
		{
			get
			{
				return this._fechaElaboracion;
			}
			set
			{
				if ((this._fechaElaboracion != value))
				{
					this.OnfechaElaboracionChanging(value);
					this.SendPropertyChanging();
					this._fechaElaboracion = value;
					this.SendPropertyChanged("fechaElaboracion");
					this.OnfechaElaboracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_importe", DbType="Float")]
		public System.Nullable<double> importe
		{
			get
			{
				return this._importe;
			}
			set
			{
				if ((this._importe != value))
				{
					this.OnimporteChanging(value);
					this.SendPropertyChanging();
					this._importe = value;
					this.SendPropertyChanged("importe");
					this.OnimporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo", DbType="VarChar(50)")]
		public string Motivo
		{
			get
			{
				return this._Motivo;
			}
			set
			{
				if ((this._Motivo != value))
				{
					this.OnMotivoChanging(value);
					this.SendPropertyChanging();
					this._Motivo = value;
					this.SendPropertyChanged("Motivo");
					this.OnMotivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(150)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRequerida", DbType="Date")]
		public System.Nullable<System.DateTime> FechaRequerida
		{
			get
			{
				return this._FechaRequerida;
			}
			set
			{
				if ((this._FechaRequerida != value))
				{
					this.OnFechaRequeridaChanging(value);
					this.SendPropertyChanging();
					this._FechaRequerida = value;
					this.SendPropertyChanged("FechaRequerida");
					this.OnFechaRequeridaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArchivoSoporte", DbType="VarChar(100)")]
		public string ArchivoSoporte
		{
			get
			{
				return this._ArchivoSoporte;
			}
			set
			{
				if ((this._ArchivoSoporte != value))
				{
					this.OnArchivoSoporteChanging(value);
					this.SendPropertyChanging();
					this._ArchivoSoporte = value;
					this.SendPropertyChanged("ArchivoSoporte");
					this.OnArchivoSoporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusRP", DbType="Int")]
		public System.Nullable<int> statusRP
		{
			get
			{
				return this._statusRP;
			}
			set
			{
				if ((this._statusRP != value))
				{
					this.OnstatusRPChanging(value);
					this.SendPropertyChanging();
					this._statusRP = value;
					this.SendPropertyChanged("statusRP");
					this.OnstatusRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusJA", DbType="Int")]
		public System.Nullable<int> statusJA
		{
			get
			{
				return this._statusJA;
			}
			set
			{
				if ((this._statusJA != value))
				{
					this.OnstatusJAChanging(value);
					this.SendPropertyChanging();
					this._statusJA = value;
					this.SendPropertyChanged("statusJA");
					this.OnstatusJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusJAC", DbType="Int")]
		public System.Nullable<int> statusJAC
		{
			get
			{
				return this._statusJAC;
			}
			set
			{
				if ((this._statusJAC != value))
				{
					this.OnstatusJACChanging(value);
					this.SendPropertyChanging();
					this._statusJAC = value;
					this.SendPropertyChanged("statusJAC");
					this.OnstatusJACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusCO", DbType="Int")]
		public System.Nullable<int> statusCO
		{
			get
			{
				return this._statusCO;
			}
			set
			{
				if ((this._statusCO != value))
				{
					this.OnstatusCOChanging(value);
					this.SendPropertyChanging();
					this._statusCO = value;
					this.SendPropertyChanged("statusCO");
					this.OnstatusCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusPresup", DbType="Int")]
		public System.Nullable<int> statusPresup
		{
			get
			{
				return this._statusPresup;
			}
			set
			{
				if ((this._statusPresup != value))
				{
					this.OnstatusPresupChanging(value);
					this.SendPropertyChanging();
					this._statusPresup = value;
					this.SendPropertyChanged("statusPresup");
					this.OnstatusPresupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idComprador", DbType="Int")]
		public System.Nullable<int> idComprador
		{
			get
			{
				return this._idComprador;
			}
			set
			{
				if ((this._idComprador != value))
				{
					this.OnidCompradorChanging(value);
					this.SendPropertyChanging();
					this._idComprador = value;
					this.SendPropertyChanged("idComprador");
					this.OnidCompradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RequiEnc_RequiDet", Storage="_RequiDet", ThisKey="idRequisicion", OtherKey="idRequiEnc")]
		public EntitySet<RequiDet> RequiDet
		{
			get
			{
				return this._RequiDet;
			}
			set
			{
				this._RequiDet.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_RequiEnc", Storage="_Proyecto", ThisKey="idProyecto", OtherKey="idProyecto", IsForeignKey=true)]
		public Proyecto Proyecto
		{
			get
			{
				return this._Proyecto.Entity;
			}
			set
			{
				Proyecto previousValue = this._Proyecto.Entity;
				if (((previousValue != value) 
							|| (this._Proyecto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proyecto.Entity = null;
						previousValue.RequiEnc.Remove(this);
					}
					this._Proyecto.Entity = value;
					if ((value != null))
					{
						value.RequiEnc.Add(this);
						this._idProyecto = value.idProyecto;
					}
					else
					{
						this._idProyecto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Proyecto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_RequiEnc", Storage="_Empleado", ThisKey="idEmpleado", OtherKey="idEmpleado", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.RequiEnc.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.RequiEnc.Add(this);
						this._idEmpleado = value.idEmpleado;
					}
					else
					{
						this._idEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RequiDet(RequiDet entity)
		{
			this.SendPropertyChanging();
			entity.RequiEnc = this;
		}
		
		private void detach_RequiDet(RequiDet entity)
		{
			this.SendPropertyChanging();
			entity.RequiEnc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RequiDet")]
	public partial class RequiDet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRequiDet;
		
		private System.Nullable<int> _idRequiEnc;
		
		private System.Nullable<int> _idProducto;
		
		private System.Nullable<double> _cantidad;
		
		private System.Nullable<double> _precio;
		
		private System.Nullable<double> _total;
		
		private string _motivo;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<RequiEnc> _RequiEnc;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRequiDetChanging(int value);
    partial void OnidRequiDetChanged();
    partial void OnidRequiEncChanging(System.Nullable<int> value);
    partial void OnidRequiEncChanged();
    partial void OnidProductoChanging(System.Nullable<int> value);
    partial void OnidProductoChanged();
    partial void OncantidadChanging(System.Nullable<double> value);
    partial void OncantidadChanged();
    partial void OnprecioChanging(System.Nullable<double> value);
    partial void OnprecioChanged();
    partial void OntotalChanging(System.Nullable<double> value);
    partial void OntotalChanged();
    partial void OnmotivoChanging(string value);
    partial void OnmotivoChanged();
    #endregion
		
		public RequiDet()
		{
			this._Producto = default(EntityRef<Producto>);
			this._RequiEnc = default(EntityRef<RequiEnc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRequiDet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRequiDet
		{
			get
			{
				return this._idRequiDet;
			}
			set
			{
				if ((this._idRequiDet != value))
				{
					this.OnidRequiDetChanging(value);
					this.SendPropertyChanging();
					this._idRequiDet = value;
					this.SendPropertyChanged("idRequiDet");
					this.OnidRequiDetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRequiEnc", DbType="Int")]
		public System.Nullable<int> idRequiEnc
		{
			get
			{
				return this._idRequiEnc;
			}
			set
			{
				if ((this._idRequiEnc != value))
				{
					if (this._RequiEnc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRequiEncChanging(value);
					this.SendPropertyChanging();
					this._idRequiEnc = value;
					this.SendPropertyChanged("idRequiEnc");
					this.OnidRequiEncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int")]
		public System.Nullable<int> idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProductoChanging(value);
					this.SendPropertyChanging();
					this._idProducto = value;
					this.SendPropertyChanged("idProducto");
					this.OnidProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Float")]
		public System.Nullable<double> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Float")]
		public System.Nullable<double> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo", DbType="VarChar(150)")]
		public string motivo
		{
			get
			{
				return this._motivo;
			}
			set
			{
				if ((this._motivo != value))
				{
					this.OnmotivoChanging(value);
					this.SendPropertyChanging();
					this._motivo = value;
					this.SendPropertyChanged("motivo");
					this.OnmotivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_RequiDet", Storage="_Producto", ThisKey="idProducto", OtherKey="idProducto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.RequiDet.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.RequiDet.Add(this);
						this._idProducto = value.idProducto;
					}
					else
					{
						this._idProducto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RequiEnc_RequiDet", Storage="_RequiEnc", ThisKey="idRequiEnc", OtherKey="idRequisicion", IsForeignKey=true)]
		public RequiEnc RequiEnc
		{
			get
			{
				return this._RequiEnc.Entity;
			}
			set
			{
				RequiEnc previousValue = this._RequiEnc.Entity;
				if (((previousValue != value) 
							|| (this._RequiEnc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RequiEnc.Entity = null;
						previousValue.RequiDet.Remove(this);
					}
					this._RequiEnc.Entity = value;
					if ((value != null))
					{
						value.RequiDet.Add(this);
						this._idRequiEnc = value.idRequisicion;
					}
					else
					{
						this._idRequiEnc = default(Nullable<int>);
					}
					this.SendPropertyChanged("RequiEnc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comprador")]
	public partial class Comprador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idComprador;
		
		private System.Nullable<int> _idEmpleado;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCompradorChanging(int value);
    partial void OnidCompradorChanged();
    partial void OnidEmpleadoChanging(System.Nullable<int> value);
    partial void OnidEmpleadoChanged();
    #endregion
		
		public Comprador()
		{
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idComprador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idComprador
		{
			get
			{
				return this._idComprador;
			}
			set
			{
				if ((this._idComprador != value))
				{
					this.OnidCompradorChanging(value);
					this.SendPropertyChanging();
					this._idComprador = value;
					this.SendPropertyChanged("idComprador");
					this.OnidCompradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int")]
		public System.Nullable<int> idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Comprador", Storage="_Empleado", ThisKey="idEmpleado", OtherKey="idEmpleado", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.Comprador.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.Comprador.Add(this);
						this._idEmpleado = value.idEmpleado;
					}
					else
					{
						this._idEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmpleado;
		
		private int _numEmp;
		
		private string _nombre;
		
		private string _apPater;
		
		private string _apMater;
		
		private int _idGpo;
		
		private string _password;
		
		private string _usuario;
		
		private EntitySet<RequiEnc> _RequiEnc;
		
		private EntitySet<Comprador> _Comprador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OnnumEmpChanging(int value);
    partial void OnnumEmpChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapPaterChanging(string value);
    partial void OnapPaterChanged();
    partial void OnapMaterChanging(string value);
    partial void OnapMaterChanged();
    partial void OnidGpoChanging(int value);
    partial void OnidGpoChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    #endregion
		
		public Empleado()
		{
			this._RequiEnc = new EntitySet<RequiEnc>(new Action<RequiEnc>(this.attach_RequiEnc), new Action<RequiEnc>(this.detach_RequiEnc));
			this._Comprador = new EntitySet<Comprador>(new Action<Comprador>(this.attach_Comprador), new Action<Comprador>(this.detach_Comprador));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numEmp", DbType="Int NOT NULL")]
		public int numEmp
		{
			get
			{
				return this._numEmp;
			}
			set
			{
				if ((this._numEmp != value))
				{
					this.OnnumEmpChanging(value);
					this.SendPropertyChanging();
					this._numEmp = value;
					this.SendPropertyChanged("numEmp");
					this.OnnumEmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apPater", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string apPater
		{
			get
			{
				return this._apPater;
			}
			set
			{
				if ((this._apPater != value))
				{
					this.OnapPaterChanging(value);
					this.SendPropertyChanging();
					this._apPater = value;
					this.SendPropertyChanged("apPater");
					this.OnapPaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apMater", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string apMater
		{
			get
			{
				return this._apMater;
			}
			set
			{
				if ((this._apMater != value))
				{
					this.OnapMaterChanging(value);
					this.SendPropertyChanging();
					this._apMater = value;
					this.SendPropertyChanged("apMater");
					this.OnapMaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGpo", DbType="Int NOT NULL")]
		public int idGpo
		{
			get
			{
				return this._idGpo;
			}
			set
			{
				if ((this._idGpo != value))
				{
					this.OnidGpoChanging(value);
					this.SendPropertyChanging();
					this._idGpo = value;
					this.SendPropertyChanged("idGpo");
					this.OnidGpoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="Char(10)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_RequiEnc", Storage="_RequiEnc", ThisKey="idEmpleado", OtherKey="idEmpleado")]
		public EntitySet<RequiEnc> RequiEnc
		{
			get
			{
				return this._RequiEnc;
			}
			set
			{
				this._RequiEnc.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Comprador", Storage="_Comprador", ThisKey="idEmpleado", OtherKey="idEmpleado")]
		public EntitySet<Comprador> Comprador
		{
			get
			{
				return this._Comprador;
			}
			set
			{
				this._Comprador.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RequiEnc(RequiEnc entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_RequiEnc(RequiEnc entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
		
		private void attach_Comprador(Comprador entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_Comprador(Comprador entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDepto;
		
		private string _nombreDepto;
		
		private System.Nullable<int> _idJefe;
		
		private EntitySet<Proyecto> _Proyecto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDeptoChanging(int value);
    partial void OnidDeptoChanged();
    partial void OnnombreDeptoChanging(string value);
    partial void OnnombreDeptoChanged();
    partial void OnidJefeChanging(System.Nullable<int> value);
    partial void OnidJefeChanged();
    #endregion
		
		public Departamento()
		{
			this._Proyecto = new EntitySet<Proyecto>(new Action<Proyecto>(this.attach_Proyecto), new Action<Proyecto>(this.detach_Proyecto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDepto
		{
			get
			{
				return this._idDepto;
			}
			set
			{
				if ((this._idDepto != value))
				{
					this.OnidDeptoChanging(value);
					this.SendPropertyChanging();
					this._idDepto = value;
					this.SendPropertyChanged("idDepto");
					this.OnidDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NombreDepto", Storage="_nombreDepto", DbType="VarChar(90)")]
		public string nombreDepto
		{
			get
			{
				return this._nombreDepto;
			}
			set
			{
				if ((this._nombreDepto != value))
				{
					this.OnnombreDeptoChanging(value);
					this.SendPropertyChanging();
					this._nombreDepto = value;
					this.SendPropertyChanged("nombreDepto");
					this.OnnombreDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJefe", DbType="Int")]
		public System.Nullable<int> idJefe
		{
			get
			{
				return this._idJefe;
			}
			set
			{
				if ((this._idJefe != value))
				{
					this.OnidJefeChanging(value);
					this.SendPropertyChanging();
					this._idJefe = value;
					this.SendPropertyChanged("idJefe");
					this.OnidJefeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Proyecto", Storage="_Proyecto", ThisKey="idDepto", OtherKey="idDepto")]
		public EntitySet<Proyecto> Proyecto
		{
			get
			{
				return this._Proyecto;
			}
			set
			{
				this._Proyecto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Proyecto(Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Proyecto(Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
	}
}
#pragma warning restore 1591
