#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SacIntegrado.UsuariosMenu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sac")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertRecurso(Recurso instance);
    partial void UpdateRecurso(Recurso instance);
    partial void DeleteRecurso(Recurso instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertClasificadorProgramatico(ClasificadorProgramatico instance);
    partial void UpdateClasificadorProgramatico(ClasificadorProgramatico instance);
    partial void DeleteClasificadorProgramatico(ClasificadorProgramatico instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SacIntegrado.Properties.Settings.Default.sacConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Recurso> Recurso
		{
			get
			{
				return this.GetTable<Recurso>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<ClasificadorFuncional> ClasificadorFuncional
		{
			get
			{
				return this.GetTable<ClasificadorFuncional>();
			}
		}
		
		public System.Data.Linq.Table<ClasificadorProgramatico> ClasificadorProgramatico
		{
			get
			{
				return this.GetTable<ClasificadorProgramatico>();
			}
		}
		
		public System.Data.Linq.Table<ActividadPoa> ActividadPoa
		{
			get
			{
				return this.GetTable<ActividadPoa>();
			}
		}
		
		public System.Data.Linq.Table<MenuBD> MenuBD
		{
			get
			{
				return this.GetTable<MenuBD>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recurso")]
	public partial class Recurso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRecurso;
		
		private string _Nombre;
		
		private System.Nullable<int> _ClavePresupuestal;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private System.Nullable<int> _AnioAplica;
		
		private System.Nullable<int> _idEmpleado;
		
		private System.Nullable<bool> _Vigente;
		
		private System.Nullable<double> _SaldoInicial;
		
		private System.Nullable<double> _SaldoFin;
		
		private string _Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRecursoChanging(int value);
    partial void OnidRecursoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnClavePresupuestalChanging(System.Nullable<int> value);
    partial void OnClavePresupuestalChanged();
    partial void OnFechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRegistroChanged();
    partial void OnAnioAplicaChanging(System.Nullable<int> value);
    partial void OnAnioAplicaChanged();
    partial void OnidEmpleadoChanging(System.Nullable<int> value);
    partial void OnidEmpleadoChanged();
    partial void OnVigenteChanging(System.Nullable<bool> value);
    partial void OnVigenteChanged();
    partial void OnSaldoInicialChanging(System.Nullable<double> value);
    partial void OnSaldoInicialChanged();
    partial void OnSaldoFinChanging(System.Nullable<double> value);
    partial void OnSaldoFinChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    #endregion
		
		public Recurso()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRecurso
		{
			get
			{
				return this._idRecurso;
			}
			set
			{
				if ((this._idRecurso != value))
				{
					this.OnidRecursoChanging(value);
					this.SendPropertyChanging();
					this._idRecurso = value;
					this.SendPropertyChanged("idRecurso");
					this.OnidRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClavePresupuestal", DbType="Int")]
		public System.Nullable<int> ClavePresupuestal
		{
			get
			{
				return this._ClavePresupuestal;
			}
			set
			{
				if ((this._ClavePresupuestal != value))
				{
					this.OnClavePresupuestalChanging(value);
					this.SendPropertyChanging();
					this._ClavePresupuestal = value;
					this.SendPropertyChanged("ClavePresupuestal");
					this.OnClavePresupuestalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="Date")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioAplica", DbType="Int")]
		public System.Nullable<int> AnioAplica
		{
			get
			{
				return this._AnioAplica;
			}
			set
			{
				if ((this._AnioAplica != value))
				{
					this.OnAnioAplicaChanging(value);
					this.SendPropertyChanging();
					this._AnioAplica = value;
					this.SendPropertyChanged("AnioAplica");
					this.OnAnioAplicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int")]
		public System.Nullable<int> idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vigente", DbType="Bit")]
		public System.Nullable<bool> Vigente
		{
			get
			{
				return this._Vigente;
			}
			set
			{
				if ((this._Vigente != value))
				{
					this.OnVigenteChanging(value);
					this.SendPropertyChanging();
					this._Vigente = value;
					this.SendPropertyChanged("Vigente");
					this.OnVigenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoInicial", DbType="Float")]
		public System.Nullable<double> SaldoInicial
		{
			get
			{
				return this._SaldoInicial;
			}
			set
			{
				if ((this._SaldoInicial != value))
				{
					this.OnSaldoInicialChanging(value);
					this.SendPropertyChanging();
					this._SaldoInicial = value;
					this.SendPropertyChanged("SaldoInicial");
					this.OnSaldoInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoFin", DbType="Float")]
		public System.Nullable<double> SaldoFin
		{
			get
			{
				return this._SaldoFin;
			}
			set
			{
				if ((this._SaldoFin != value))
				{
					this.OnSaldoFinChanging(value);
					this.SendPropertyChanging();
					this._SaldoFin = value;
					this.SendPropertyChanged("SaldoFin");
					this.OnSaldoFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(150)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmpleado;
		
		private string _Nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Empleado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClasificadorFuncional")]
	public partial class ClasificadorFuncional
	{
		
		private int _idClasifFuncional;
		
		private string _Nombre;
		
		public ClasificadorFuncional()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasifFuncional", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int idClasifFuncional
		{
			get
			{
				return this._idClasifFuncional;
			}
			set
			{
				if ((this._idClasifFuncional != value))
				{
					this._idClasifFuncional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClasificadorProgramatico")]
	public partial class ClasificadorProgramatico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idClasifProgramatico;
		
		private string _Nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClasifProgramaticoChanging(int value);
    partial void OnidClasifProgramaticoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public ClasificadorProgramatico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClasifProgramatico", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idClasifProgramatico
		{
			get
			{
				return this._idClasifProgramatico;
			}
			set
			{
				if ((this._idClasifProgramatico != value))
				{
					this.OnidClasifProgramaticoChanging(value);
					this.SendPropertyChanging();
					this._idClasifProgramatico = value;
					this.SendPropertyChanged("idClasifProgramatico");
					this.OnidClasifProgramaticoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActividadPoa")]
	public partial class ActividadPoa
	{
		
		private System.Nullable<int> _idActPoa;
		
		private string _Nombre;
		
		public ActividadPoa()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idActPoa", DbType="Int")]
		public System.Nullable<int> idActPoa
		{
			get
			{
				return this._idActPoa;
			}
			set
			{
				if ((this._idActPoa != value))
				{
					this._idActPoa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class MenuBD
	{
		
		private int _idMenu;
		
		private string _Nombre;
		
		private string _variable;
		
		public MenuBD()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMenu", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int idMenu
		{
			get
			{
				return this._idMenu;
			}
			set
			{
				if ((this._idMenu != value))
				{
					this._idMenu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="Char(30)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_variable", DbType="Char(20)")]
		public string variable
		{
			get
			{
				return this._variable;
			}
			set
			{
				if ((this._variable != value))
				{
					this._variable = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
